#!/usr/bin/env bash
# =====================================================================
#  lap-monitor - installer
#  Installs dependencies, creates config + data dir, and registers a
#  systemd service that runs headless and auto-starts on boot.
#
#  Usage:  bash install.sh
#  Run as root, or as a user with sudo. (Both work.)
# =====================================================================
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_NAME="lap-monitor"
PYTHON="$(command -v python3 || true)"

# Use sudo only when we're not already root. On minimal Debian (root, no sudo
# installed) this runs commands directly.
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
  SERVICE_USER="${SUDO_USER:-root}"
elif command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
  SERVICE_USER="$(id -un)"
else
  echo "!! Need root privileges (or 'sudo'). Re-run as root: su -c 'bash install.sh'"
  exit 1
fi

echo "==> lap-monitor installer"
echo "    App dir : $APP_DIR"
echo "    Service runs as user: $SERVICE_USER"

if [ -z "$PYTHON" ]; then
  echo "!! python3 not found. Install it first: apt install -y python3 python3-pip"
  exit 1
fi

# --- 1) Dependencies ---
echo "==> Installing Python dependencies..."
if pip3 install -r "$APP_DIR/requirements.txt" --break-system-packages 2>/dev/null; then
  :
else
  pip3 install -r "$APP_DIR/requirements.txt"
fi
# ICMP ping tool (for ping checks)
if ! command -v ping >/dev/null 2>&1; then
  echo "==> Installing iputils-ping..."
  $SUDO apt-get install -y iputils-ping || true
fi

# --- 2) Config + data dir (don't overwrite existing) ---
echo "==> Preparing config and data directory..."
mkdir -p "$APP_DIR/data"
[ -f "$APP_DIR/config.yaml" ] || cp "$APP_DIR/config.example.yaml" "$APP_DIR/config.yaml"

# --- 3) 'lap-monitor' CLI command on PATH ---
BIN="/usr/local/bin/lap-monitor"
echo "==> Installing CLI command: $BIN"
$SUDO tee "$BIN" >/dev/null <<EOF
#!/usr/bin/env bash
# lap-monitor launcher (generated by install.sh)
cd "${APP_DIR}" && exec ${PYTHON} -m lap_monitor "\$@"
EOF
$SUDO chmod +x "$BIN"

# Short alias so you can type 'lapm' instead of 'lap-monitor'.
$SUDO ln -sf "$BIN" /usr/local/bin/lapm
echo "==> Installed short alias: lapm -> lap-monitor"

# --- 4) systemd service (auto-start on boot, auto-restart on crash) ---
if command -v systemctl >/dev/null 2>&1; then
  UNIT="/etc/systemd/system/${SERVICE_NAME}.service"
  echo "==> Installing systemd service: $UNIT"
  $SUDO tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=lap-monitor (headless website/VPS monitoring service)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${APP_DIR}
ExecStart=${PYTHON} -m lap_monitor serve
Restart=always
RestartSec=5
# Keep it light on the 2GB device
MemoryMax=80M
Nice=10

[Install]
WantedBy=multi-user.target
EOF

  $SUDO systemctl daemon-reload
  $SUDO systemctl enable --now "${SERVICE_NAME}.service"
  echo "==> Service installed and started (auto-starts on boot)."
  echo "    Status:  systemctl status ${SERVICE_NAME}"
  echo "    Logs:    journalctl -u ${SERVICE_NAME} -f"
else
  echo "!! systemctl not found - skipping service install."
  echo "   Run manually instead:  python3 -m lap_monitor serve"
fi

echo ""
echo "==> Done. Next steps ('lap-monitor' or the short alias 'lapm' work anywhere now):"
echo "      lapm add http https://example.com"
echo "      lapm add ping 1.1.1.1"
echo "      lapm add tcp 10.0.0.5:22"
echo "      lapm list"
echo "      $SUDO systemctl restart lap-monitor    # apply target changes"
echo "      lapm dashboard                         # watch the live screen"
( cd "$APP_DIR" && "$PYTHON" -m lap_monitor --version )
