#!/usr/bin/env bash
# =====================================================================
#  lap-monitor - installer
#  Installs dependencies, creates config + data dir, and registers a
#  systemd service that runs headless and auto-starts on boot.
#
#  Usage:  bash install.sh
#  (needs sudo for the systemd parts; it will prompt when required)
# =====================================================================
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_NAME="lap-monitor"
SERVICE_USER="${SUDO_USER:-$(id -un)}"
PYTHON="$(command -v python3 || true)"

echo "==> lap-monitor installer"
echo "    App dir : $APP_DIR"
echo "    User    : $SERVICE_USER"

if [ -z "$PYTHON" ]; then
  echo "!! python3 not found. Install it first: sudo apt install -y python3 python3-pip"
  exit 1
fi

# --- 1) Dependencies ---
echo "==> Installing Python dependencies..."
if pip3 install -r "$APP_DIR/requirements.txt" --break-system-packages 2>/dev/null; then
  :
else
  pip3 install -r "$APP_DIR/requirements.txt"
fi
# ICMP ping tool (for ping checks)
if ! command -v ping >/dev/null 2>&1; then
  echo "==> Installing iputils-ping..."
  sudo apt-get install -y iputils-ping || true
fi

# --- 2) Config + data dir (don't overwrite existing) ---
echo "==> Preparing config and data directory..."
mkdir -p "$APP_DIR/data"
[ -f "$APP_DIR/config.yaml" ] || cp "$APP_DIR/config.example.yaml" "$APP_DIR/config.yaml"

# --- 3) 'lap-monitor' CLI command on PATH ---
BIN="/usr/local/bin/lap-monitor"
echo "==> Installing CLI command: $BIN"
sudo tee "$BIN" >/dev/null <<EOF
#!/usr/bin/env bash
# lap-monitor launcher (generated by install.sh)
cd "${APP_DIR}" && exec ${PYTHON} -m lap_monitor "\$@"
EOF
sudo chmod +x "$BIN"

# --- 4) systemd service (auto-start on boot, auto-restart on crash) ---
if command -v systemctl >/dev/null 2>&1; then
  UNIT="/etc/systemd/system/${SERVICE_NAME}.service"
  echo "==> Installing systemd service: $UNIT"
  sudo tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=lap-monitor (headless website/VPS monitoring service)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${APP_DIR}
ExecStart=${PYTHON} -m lap_monitor serve
Restart=always
RestartSec=5
# Keep it light on the 2GB device
MemoryMax=80M
Nice=10

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable --now "${SERVICE_NAME}.service"
  echo "==> Service installed and started (auto-starts on boot)."
  echo "    Status:  systemctl status ${SERVICE_NAME}"
  echo "    Logs:    journalctl -u ${SERVICE_NAME} -f"
else
  echo "!! systemctl not found - skipping service install."
  echo "   Run manually instead:  python3 -m lap_monitor serve"
fi

echo ""
echo "==> Done. Next steps (you can now use the 'lap-monitor' command anywhere):"
echo "      lap-monitor add http https://example.com"
echo "      lap-monitor add ping 1.1.1.1"
echo "      lap-monitor add tcp 10.0.0.5:22"
echo "      lap-monitor list"
echo "      sudo systemctl restart lap-monitor    # apply target changes"
echo "      lap-monitor dashboard                 # watch the live screen"
( cd "$APP_DIR" && "$PYTHON" -m lap_monitor --version )
